const list = [
    {
      id: 1,
      title: "Panda",
      author: "by Rebecca Smith | 14 Dec 2021",
      price: 234,
      img: "https://source.unsplash.com/400x300/?panda",
      amount: 1,
    },
    {
      id: 2,
      title: "Tiger",
      author: "by John Doe | 10 Jan 2022",
      price: 299,
      img: "https://source.unsplash.com/400x300/?tiger",
      amount: 1,
    },
    {
      id: 3,
      title: "Mountain",
      author: "by Alice Brown | 05 Feb 2022",
      price: 180,
      img: "https://source.unsplash.com/400x300/?mountain",
      amount: 1,
    },
    {
      id: 4,
      title: "Sunset",
      author: "by Mark Wilson | 22 Mar 2022",
      price: 220,
      img: "https://source.unsplash.com/400x300/?sunset",
      amount: 1,
    },
    {
      id: 5,
      title: "Beach",
      author: "by Sarah Connor | 12 Apr 2022",
      price: 210,
      img: "https://source.unsplash.com/400x300/?beach",
      amount: 1,
    },
    {
      id: 6,
      title: "Cityscape",
      author: "by David Lee | 30 May 2022",
      price: 250,
      img: "https://source.unsplash.com/400x300/?city",
      amount: 1,
    },
    {
      id: 7,
      title: "Books",
      author: "by Emily Johnson | 07 Jun 2022",
      price: 175,
      img: "https://source.unsplash.com/400x300/?books",
      amount: 1,
    },
    {
      id: 8,
      title: "Coffee",
      author: "by Alex Martin | 19 Jul 2022",
      price: 130,
      img: "https://source.unsplash.com/400x300/?coffee",
      amount: 1,
    },
    {
      id: 9,
      title: "Bicycle",
      author: "by Michael Scott | 23 Aug 2022",
      price: 145,
      img: "https://source.unsplash.com/400x300/?bicycle",
      amount: 1,
    },
    {
      id: 10,
      title: "Rainforest",
      author: "by Olivia White | 14 Sep 2022",
      price: 270,
      img: "https://source.unsplash.com/400x300/?rainforest",
      amount: 1,
    },
    {
      id: 11,
      title: "Galaxy",
      author: "by Brian Adams | 03 Oct 2022",
      price: 290,
      img: "https://source.unsplash.com/400x300/?galaxy",
      amount: 1,
    },
    {
      id: 12,
      title: "Dogs",
      author: "by Sophia Carter | 18 Nov 2022",
      price: 199,
      img: "https://source.unsplash.com/400x300/?dog",
      amount: 1,
    },
    {
      id: 13,
      title: "Cats",
      author: "by Ethan Brown | 25 Dec 2022",
      price: 195,
      img: "https://source.unsplash.com/400x300/?cat",
      amount: 1,
    },
    {
      id: 14,
      title: "Flowers",
      author: "by Ava Green | 02 Jan 2023",
      price: 155,
      img: "https://source.unsplash.com/400x300/?flowers",
      amount: 1,
    },
    {
      id: 15,
      title: "Space",
      author: "by Liam Miller | 10 Feb 2023",
      price: 310,
      img: "https://source.unsplash.com/400x300/?space",
      amount: 1,
    },
    {
      id: 16,
      title: "Desert",
      author: "by Harper Wilson | 22 Mar 2023",
      price: 190,
      img: "https://source.unsplash.com/400x300/?desert",
      amount: 1,
    },
    {
      id: 17,
      title: "Bridge",
      author: "by Noah Anderson | 15 Apr 2023",
      price: 260,
      img: "https://source.unsplash.com/400x300/?bridge",
      amount: 1,
    },
    {
      id: 18,
      title: "Forest",
      author: "by Isabella Hall | 27 May 2023",
      price: 215,
      img: "https://source.unsplash.com/400x300/?forest",
      amount: 1,
    },
    {
      id: 19,
      title: "Lake",
      author: "by Mason Young | 12 Jun 2023",
      price: 240,
      img: "https://source.unsplash.com/400x300/?lake",
      amount: 1,
    },
    {
      id: 20,
      title: "Castle",
      author: "by Charlotte Scott | 08 Jul 2023",
      price: 350,
      img: "https://source.unsplash.com/400x300/?castle",
      amount: 1,
    }
  ];
  
  export default list;
  